apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app1
  namespace: default
spec:
  project: default
  source:
    repoURL: https://github.com/agaream/helm-repos.git
    path: app-of-apps/apps/app1
    targetRevision: HEAD
    helm:
      valueFiles:
        - values-stg.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dom1
  syncPolicy:
    automated: {}