apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app2
  namespace: default
spec:
  project: default
  source:
    repoURL: https://github.com/agaream/helm-repos.git
    path: weather-api/helm-chart
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dom1
  syncPolicy:
    automated: {}